[book]
title = "Learn Rust in 500 Lines"
authors = []
language = "en"

[build]
build-dir = "../../book"
create-missing = true

[output.html]
additional-js = ["theme/lang-switcher.js"]
additional-css = ["theme/lang-switcher.css"]
git-repository-url = "https://github.com/EricWvi/learn-rust-in-500-lines"
